#! /usr/bin/env python
# Copyright (C) 2017 Paulo V. C. Medeiros
# A python wrapper to BandUP and its plotting tool
# This file is part of BandUP: Band Unfolding code for Plane-wave based calculations.
#
# BandUP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
#  BandUP is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with BandUP.  If not, see <http://www.gnu.org/licenses/>.
from bandup_python_wrapper.argparse_wrapper import BandUpPythonArgumentParser
from bandup_python_wrapper.files import (
    mkdir,
    create_bandup_input,
)
from bandup_python_wrapper.runners import run_bandup

parser = BandUpPythonArgumentParser()
args = parser.parse_args()

if(args.main_task=='unfold'):
    mkdir(args.results_dir,  True)
    create_bandup_input(args)
    run_bandup(args)
elif(args.main_task=='plot'):
    print args.clip_spin
    #plot = BandUpPlot(parser)
elif(args.main_task=='pre-unfold'):
   pass
else:
    print 'Task "%s" not available.'%(args.main_task)



